application: bandmebags
version: 1
runtime: python
api_version: 1
threadsafe: yes

handlers:

- url: /(.+)
  static_files: public/\1
  upload: public/(.*)

- url: /
  static_files: public/index.html
  upload: public/index.html

skip_files:
- ^(.*/)?app\.yaml
- ^README
- ^\.gitignore
- ^\.git/.*
